services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/certs:/etc/ssl/certs:ro
    ports:
      - '8080:80'
      - '8443:443'
    networks:
      - transcendence_net
    depends_on:
      backend:
        condition: service_started
      websocket:
        condition: service_started
      frontend:
        condition: service_healthy
  frontend:
    build: ./frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - backend
    networks:
      - transcendence_net
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploadss
  websocket:
    build: ./websocket
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    networks:
      - transcendence_net
    volumes:
      - ./websocket:/app
      - /app/node_modules
      - ./database:/database
  backend:
    build: ./backend
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - transcendence_net
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./database:/database

  database:
    build: ./database
    volumes:
      - ./database:/database
    networks:
      - transcendence_net

networks:
  transcendence_net:
    driver: bridge