services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - transcendence_net
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - transcendence_net
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./database:/database

  database:
    build: ./database
    volumes:
      - ./database:/database
    networks:
      - transcendence_net

networks:
  transcendence_net:
    driver: bridge
